create table "public"."errors" (
    "id" bigint generated by default as identity not null,
    "details" text,
    "hint" text,
    "code" text
);


alter table "public"."errors" enable row level security;

CREATE UNIQUE INDEX errors_id_key ON public.errors USING btree (id);

CREATE UNIQUE INDEX errors_pkey ON public.errors USING btree (id);

alter table "public"."errors" add constraint "errors_pkey" PRIMARY KEY using index "errors_pkey";

alter table "public"."errors" add constraint "errors_id_key" UNIQUE using index "errors_id_key";

grant delete on table "public"."errors" to "anon";

grant insert on table "public"."errors" to "anon";

grant references on table "public"."errors" to "anon";

grant select on table "public"."errors" to "anon";

grant trigger on table "public"."errors" to "anon";

grant truncate on table "public"."errors" to "anon";

grant update on table "public"."errors" to "anon";

grant delete on table "public"."errors" to "authenticated";

grant insert on table "public"."errors" to "authenticated";

grant references on table "public"."errors" to "authenticated";

grant select on table "public"."errors" to "authenticated";

grant trigger on table "public"."errors" to "authenticated";

grant truncate on table "public"."errors" to "authenticated";

grant update on table "public"."errors" to "authenticated";

grant delete on table "public"."errors" to "service_role";

grant insert on table "public"."errors" to "service_role";

grant references on table "public"."errors" to "service_role";

grant select on table "public"."errors" to "service_role";

grant trigger on table "public"."errors" to "service_role";

grant truncate on table "public"."errors" to "service_role";

grant update on table "public"."errors" to "service_role";

alter table "public"."errors" add column "created_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text);