create type "public"."stage_types" as enum ('qualifiers', 'pvp');

revoke delete on table "public"."mappools" from "anon";

revoke insert on table "public"."mappools" from "anon";

revoke references on table "public"."mappools" from "anon";

revoke select on table "public"."mappools" from "anon";

revoke trigger on table "public"."mappools" from "anon";

revoke truncate on table "public"."mappools" from "anon";

revoke update on table "public"."mappools" from "anon";

revoke delete on table "public"."mappools" from "authenticated";

revoke insert on table "public"."mappools" from "authenticated";

revoke references on table "public"."mappools" from "authenticated";

revoke select on table "public"."mappools" from "authenticated";

revoke trigger on table "public"."mappools" from "authenticated";

revoke truncate on table "public"."mappools" from "authenticated";

revoke update on table "public"."mappools" from "authenticated";

revoke delete on table "public"."mappools" from "service_role";

revoke insert on table "public"."mappools" from "service_role";

revoke references on table "public"."mappools" from "service_role";

revoke select on table "public"."mappools" from "service_role";

revoke trigger on table "public"."mappools" from "service_role";

revoke truncate on table "public"."mappools" from "service_role";

revoke update on table "public"."mappools" from "service_role";

alter table "public"."mappool_maps" drop constraint "mappool_maps_mappool_id_fkey";

alter table "public"."mappools" drop constraint "mappools_tournament_id_fkey";

alter table "public"."mappools" drop constraint "mappools_pkey";

drop index if exists "public"."mappools_pkey";

drop table "public"."mappools";

create table "public"."qualifier_lobbies" (
    "id" integer generated by default as identity not null,
    "tournament_match_id" text not null,
    "lobby_time" timestamp with time zone not null,
    "referee_id" integer,
    "mp_id" integer,
    "stage_id" integer not null
);


alter table "public"."qualifier_lobbies" enable row level security;

create table "public"."qualifier_signups" (
    "id" integer generated by default as identity not null,
    "signed_up_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "user_id" integer not null,
    "lobby_id" integer not null
);


alter table "public"."qualifier_signups" enable row level security;

create table "public"."tournament_stages" (
    "id" integer generated by default as identity not null,
    "tournament_id" integer not null,
    "stage_name" text not null,
    "stage_index" smallint not null,
    "stage_type" stage_types not null
);


alter table "public"."tournament_stages" enable row level security;

alter table "public"."mappool_maps" drop column "mappool_id";

alter table "public"."mappool_maps" add column "mods" text;

alter table "public"."mappool_maps" add column "stage_id" integer not null;

alter table "public"."matches" add column "stage_id" integer not null;

alter table "public"."matches" alter column "tournament_match_id" set data type text using "tournament_match_id"::text;

alter table "public"."registrations" alter column "registered_at" set default (now() AT TIME ZONE 'utc'::text);

CREATE UNIQUE INDEX qualifier_lobbies_mp_id_key ON public.qualifier_lobbies USING btree (mp_id);

CREATE UNIQUE INDEX qualifier_lobbies_pkey ON public.qualifier_lobbies USING btree (id);

CREATE UNIQUE INDEX qualifier_signups_pkey ON public.qualifier_signups USING btree (id);

CREATE UNIQUE INDEX tournament_stages_pkey ON public.tournament_stages USING btree (id);

alter table "public"."qualifier_lobbies" add constraint "qualifier_lobbies_pkey" PRIMARY KEY using index "qualifier_lobbies_pkey";

alter table "public"."qualifier_signups" add constraint "qualifier_signups_pkey" PRIMARY KEY using index "qualifier_signups_pkey";

alter table "public"."tournament_stages" add constraint "tournament_stages_pkey" PRIMARY KEY using index "tournament_stages_pkey";

alter table "public"."mappool_maps" add constraint "mappool_maps_stage_id_fkey" FOREIGN KEY (stage_id) REFERENCES tournament_stages(id) not valid;

alter table "public"."mappool_maps" validate constraint "mappool_maps_stage_id_fkey";

alter table "public"."matches" add constraint "matches_stage_id_fkey" FOREIGN KEY (stage_id) REFERENCES tournament_stages(id) not valid;

alter table "public"."matches" validate constraint "matches_stage_id_fkey";

alter table "public"."qualifier_lobbies" add constraint "qualifier_lobbies_mp_id_key" UNIQUE using index "qualifier_lobbies_mp_id_key";

alter table "public"."qualifier_lobbies" add constraint "qualifier_lobbies_referee_id_fkey" FOREIGN KEY (referee_id) REFERENCES referees(id) not valid;

alter table "public"."qualifier_lobbies" validate constraint "qualifier_lobbies_referee_id_fkey";

alter table "public"."qualifier_lobbies" add constraint "qualifier_lobbies_stage_id_fkey" FOREIGN KEY (stage_id) REFERENCES tournament_stages(id) not valid;

alter table "public"."qualifier_lobbies" validate constraint "qualifier_lobbies_stage_id_fkey";

alter table "public"."qualifier_signups" add constraint "qualifier_signups_lobby_id_fkey" FOREIGN KEY (lobby_id) REFERENCES qualifier_lobbies(id) not valid;

alter table "public"."qualifier_signups" validate constraint "qualifier_signups_lobby_id_fkey";

alter table "public"."qualifier_signups" add constraint "qualifier_signups_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."qualifier_signups" validate constraint "qualifier_signups_user_id_fkey";

alter table "public"."tournament_stages" add constraint "tournament_stages_tournament_id_fkey" FOREIGN KEY (tournament_id) REFERENCES tournaments(id) not valid;

alter table "public"."tournament_stages" validate constraint "tournament_stages_tournament_id_fkey";

grant delete on table "public"."qualifier_lobbies" to "anon";

grant insert on table "public"."qualifier_lobbies" to "anon";

grant references on table "public"."qualifier_lobbies" to "anon";

grant select on table "public"."qualifier_lobbies" to "anon";

grant trigger on table "public"."qualifier_lobbies" to "anon";

grant truncate on table "public"."qualifier_lobbies" to "anon";

grant update on table "public"."qualifier_lobbies" to "anon";

grant delete on table "public"."qualifier_lobbies" to "authenticated";

grant insert on table "public"."qualifier_lobbies" to "authenticated";

grant references on table "public"."qualifier_lobbies" to "authenticated";

grant select on table "public"."qualifier_lobbies" to "authenticated";

grant trigger on table "public"."qualifier_lobbies" to "authenticated";

grant truncate on table "public"."qualifier_lobbies" to "authenticated";

grant update on table "public"."qualifier_lobbies" to "authenticated";

grant delete on table "public"."qualifier_lobbies" to "service_role";

grant insert on table "public"."qualifier_lobbies" to "service_role";

grant references on table "public"."qualifier_lobbies" to "service_role";

grant select on table "public"."qualifier_lobbies" to "service_role";

grant trigger on table "public"."qualifier_lobbies" to "service_role";

grant truncate on table "public"."qualifier_lobbies" to "service_role";

grant update on table "public"."qualifier_lobbies" to "service_role";

grant delete on table "public"."qualifier_signups" to "anon";

grant insert on table "public"."qualifier_signups" to "anon";

grant references on table "public"."qualifier_signups" to "anon";

grant select on table "public"."qualifier_signups" to "anon";

grant trigger on table "public"."qualifier_signups" to "anon";

grant truncate on table "public"."qualifier_signups" to "anon";

grant update on table "public"."qualifier_signups" to "anon";

grant delete on table "public"."qualifier_signups" to "authenticated";

grant insert on table "public"."qualifier_signups" to "authenticated";

grant references on table "public"."qualifier_signups" to "authenticated";

grant select on table "public"."qualifier_signups" to "authenticated";

grant trigger on table "public"."qualifier_signups" to "authenticated";

grant truncate on table "public"."qualifier_signups" to "authenticated";

grant update on table "public"."qualifier_signups" to "authenticated";

grant delete on table "public"."qualifier_signups" to "service_role";

grant insert on table "public"."qualifier_signups" to "service_role";

grant references on table "public"."qualifier_signups" to "service_role";

grant select on table "public"."qualifier_signups" to "service_role";

grant trigger on table "public"."qualifier_signups" to "service_role";

grant truncate on table "public"."qualifier_signups" to "service_role";

grant update on table "public"."qualifier_signups" to "service_role";

grant delete on table "public"."tournament_stages" to "anon";

grant insert on table "public"."tournament_stages" to "anon";

grant references on table "public"."tournament_stages" to "anon";

grant select on table "public"."tournament_stages" to "anon";

grant trigger on table "public"."tournament_stages" to "anon";

grant truncate on table "public"."tournament_stages" to "anon";

grant update on table "public"."tournament_stages" to "anon";

grant delete on table "public"."tournament_stages" to "authenticated";

grant insert on table "public"."tournament_stages" to "authenticated";

grant references on table "public"."tournament_stages" to "authenticated";

grant select on table "public"."tournament_stages" to "authenticated";

grant trigger on table "public"."tournament_stages" to "authenticated";

grant truncate on table "public"."tournament_stages" to "authenticated";

grant update on table "public"."tournament_stages" to "authenticated";

grant delete on table "public"."tournament_stages" to "service_role";

grant insert on table "public"."tournament_stages" to "service_role";

grant references on table "public"."tournament_stages" to "service_role";

grant select on table "public"."tournament_stages" to "service_role";

grant trigger on table "public"."tournament_stages" to "service_role";

grant truncate on table "public"."tournament_stages" to "service_role";

grant update on table "public"."tournament_stages" to "service_role";