name: Deploy Migrations to Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link supabase
        run: SUPABASE_DB_PASSWORD=$PRODUCTION_DB_PASSWORD supabase link --project-ref ${{ secrets.PRODUCTION_PROJECT_ID }} -p ${{ secrets.PRODUCTION_DB_PASSWORD }} --debug

      - run: SUPABASE_DB_PASSWORD=$PRODUCTION_DB_PASSWORD supabase db push -p ${{ secrets.PRODUCTION_DB_PASSWORD }} --debug
