name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set database URL based on branch
        run: echo "SUPABASE_DB_URL=$SUPABASE_DB_URL" >> $GITHUB_ENV

      - name: Apply Supabase migrations
        run: supabase db push --db-url $SUPABASE_DB_URL
